(#142) relocate task scripts in spooldir
choria-io/mcorpc-ruby-support pull request #143
Opened 2021-03-03 20:28 UTC by smortex

When setting up the spooldir, ensure the actual task entry point is copied as `<module name>/tasks/<task-name>`.  This way, tasks referring to other resources using relative path will be able to find them.

Fixes #142

2021-03-03 23:48 UTC, smortex commented
Hum…  It looks like the JSON loaded by the unit test does not look like the JSON returned by the PuppetServer API endpoint.  I added a few commits to fix this.

@neomilium, do you still have a real-world non-working setup that can be used to check if this fix your issue?

2021-03-04 11:16 UTC, ripienaar requested changes
looks good, minor changes only

2021-03-04 11:16 UTC, ripienaar commented on lib/mcollective/util/tasks_support.rb
> +      # Return a task's module
new line below

2021-03-04 11:16 UTC, ripienaar commented on lib/mcollective/util/tasks_support.rb
> +      # @return [String] the module name
add here ```@raise [StandardError] for invalid task names``` since `parse_task` can fail

2021-03-04 18:23 UTC, ripienaar commented
looks good, you're ready for me to merge?

2021-03-04 18:52 UTC, smortex commented
@ripienaar it was okay with my local tests but @neomilium has a real world problem that should be fixed by this and I would like to have feedback from him to be sure it is okay :grin:.

@neomilium overwriting the file directly on the node where the task is run should do it (maybe adjust the Ruby version if the node is not running Puppet 7):

```
# curl -o /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.24.1/lib/mcollective/util/tasks_support.rb \
  https://raw.githubusercontent.com/smortex/mcorpc-ruby-support/relocate-task-file/lib/mcollective/util/tasks_support.rb
```

Does it fix your issue?

2021-03-11 19:02 UTC, neomilium commented
I just tested the patch, it works! Thanks

2021-03-11 19:02 UTC, neomilium commented
@ripienaar Ready to merge :-)

2021-03-11 19:04 UTC, merged

2021-03-11 19:05 UTC, ripienaar commented
Thank you @neomilium and @smortex :)