Allow to run tasks as another user
choria-io/mcorpc-ruby-support pull request #91
Opened 2020-12-29 21:24 UTC by smortex

This is part of https://github.com/choria-io/mcollective-choria/issues/439

Environment is currently not reset (e.g. `$HOME`, `$USER`, `$LOGNAME` are still showing calling processes values).  When running a task that shows output of `id(1)` and `env(1)` with `mco tasks run testmodule::testtask --run-as romain -I $(hostname -f)` I get this:

```
===> id
uid=1000(romain) gid=1000(romain) groupes=1000(romain)
===> env
LC_TIME=fr_FR.UTF-8
USER=root
HOME=/root
LC_MONETARY=fr_FR.UTF-8
LOGNAME=root
JOURNAL_STREAM=9:247574
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
INVOCATION_ID=dc6dbb00fb054c5bbc973e59a24a3fb4
PT__installdir=/opt/puppetlabs/mcollective/tasks-spool/878eb6153e5a50f1927647309ce5df6f/files
LC_ADDRESS=fr_FR.UTF-8
_task=testmodule::testtask
LANG=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
_choria_task_caller=choria=romain.mcollective
LC_NAME=fr_FR.UTF-8
SHELL=/bin/sh
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
_choria_task_id=878eb6153e5a50f1927647309ce5df6f
PWD=/
LC_NUMERIC=fr_FR.UTF-8
LC_PAPER=fr_FR.UTF-8
```

2020-12-29 21:27 UTC, ripienaar commented
Will check in the morning. Pls also do the PR you did against the tasks module here. 

You caught me mid figuring out where these go but I suspect they will go here and the task module will have a rake task to get them from here. This is where all the tests and stuff are. 

Not sure yet. But for now making it here is safest

2020-12-29 23:20 UTC, smortex commented
I am not sure about the way you would like me to include this, so I amended my commit, but will rework it according to your needs on request ;-)

2020-12-29 23:30 UTC, smortex commented
Some bits are still missing, not providing the optional run_as return an error:

```
The tasks application failed to run: Cannot validate input run_as: value should be a string
```

Investigating…

2020-12-30 11:02 UTC, ripienaar requested changes
nice one

2020-12-30 11:02 UTC, ripienaar commented on lib/mcollective/agent/bolt_tasks.ddl
> +        :maxlength   => 32
maybe add `:default => ""` to these

2020-12-30 19:44 UTC, smortex commented on lib/mcollective/util/tasks_support.rb
> +      def spawn_command(command, environment, stdin, spooldir, run_as)
Fixed!

2020-12-30 19:46 UTC, smortex commented on lib/mcollective/agent/bolt_tasks.ddl
> +        :maxlength   => 32
I think `:default => nil` is more suitable since the field is optional?  It's what `ddl2json` generates in the .json file when do `:default` is provided in the ddl.

2020-12-30 19:50 UTC, ripienaar commented on lib/mcollective/agent/bolt_tasks.ddl
> +        :maxlength   => 32
It's a string though, so from the perspective of go nil is not a valid string - it would end up "" anyway :) Though I guess it becomes unset and so ruby ends up doing the nil thing so the end result is sane as far as ruby goes.  But given the type is string we should probably default to a string too.

But whatever, leave as is and we fix if it causes issues, I think I catered for this case in the go DDL code

2020-12-30 19:50 UTC, ripienaar approved these changes

2020-12-30 19:50 UTC, ripienaar commented
You're ready for me to merge this @smortex ?

2020-12-30 19:56 UTC, smortex commented
OK for me!  Thanks!

2020-12-31 07:45 UTC, merged